### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by hortemo** [MustansirZia/react-native-fused-location#13]
Hi! Could you please add the timestamp (location.getTime()) to the location object? Kind regards

**Comment by MustansirZia** [comment]
Hi @hortemo!
Of course. The newest update of `0.0.11` has this. f57113533088817713e79b41fe76474d70ac0bc0. You can safely update your package to `0.0.11`.

**Comment by hortemo** [comment]
Thank you! Why did you add it as a string rather than an integer?

**Comment by MustansirZia** [comment]
This is because JavaScript doesn't have support for long and thus react native's `WritableMap` doesn't have a `putLong` method. I could use a `putDouble` too but felt there would be no chance for a truncation if I used a string. Hope that clears it! :)
Read up this [issue](https://github.com/facebook/react-native/issues/9685) for react native for more.
