### ISSUE TITLE
Where should i place the `<permission>` tag?

### ISSUE THREAD

**Issue by theapache64** [MustansirZia/react-native-fused-location#31]
In `AndroidManifest.xml`, when should i place the `<permission>` tags. As direct child of `<application>` or `activity` ? Is it mandatory ? What's the purpose of setting the tag from `uses-permission` ?

**Comment by MustansirZia** [comment]
Hi @theapache64! In React Native It's the same thing whether to place it under `<application>` or `<activity>` since in 90% of cases RN uses a single activity to render all of the app. (i.e `MainActivity` or `ExpoActivity`). But I would recommend placing it under `<application>` so it will cover all use cases and the permission would work everywhere in all activites.

As for `uses-permission`, it simply affects how the app is filtered in PlayStore. It is to highlight that the app uses a particular permission inside of PlayStore. Read more about it from [here](https://developer.android.com/guide/topics/manifest/uses-permission-element).

**Comment by theapache64** [comment]
(y)
