### ISSUE TITLE
Build fail when adding `permission` tag in AndroidManifest.xml

### ISSUE THREAD

**Issue by grifotv** [MustansirZia/react-native-fused-location#41]
I'm getting the following error after adding the `<permission>` tag within the `<application>` tag.

```
> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  /my_project_path/android/app/build/intermediates/merged_manifests/debug/AndroidManifest.xml:46: AAPT: error: unexpected element <permission> found in <manifest><application>.
      
  /my_project_path/android/app/build/intermediates/merged_manifests/debug/AndroidManifest.xml:49: AAPT: error: unexpected element <permission> found in <manifest><application>.
```

Are these tags really necessary or `<uses-permission>` tags should be enough?

Related to #31

**Comment by MustansirZia** [comment]
Hi @grifotv! 
Well, ideally you would want both but `<uses-permission>` should be enough too. Do paste your manifest file here if you still face issues.

**Comment by MustansirZia** [comment]
Hi @grifotv! 
Well, ideally you would want both but `<uses-permission>` should be enough too. Do paste your manifest file here if you still face issues.

I don't see it as being related to #31 although you could place both these tags inside your `<activity>` tags too to see if it works since a react native application usually has a single activity.

**Comment by MustansirZia** [comment]
Feel free to close the issue if you're satisfied.
