### ISSUE TITLE
Location object does not have a heading property

### ISSUE THREAD

**Issue by Malcolm1998** [MustansirZia/react-native-fused-location#44]
When I used the example code in the docs, the location object that is returned does not have a heading property. Other important properties are returned like latitude and longitude, but the heading property is missing all together. However, the the documentation says that a heading property should be in the location object. I am testing the code on my Samsung Galaxy S8 that is running android 9.

**Comment by MustansirZia** [comment]
Hi @Malcolm1998! 
I understand what you're saying. This looks it can be fixed pretty soon. I'm certain that means in the next version. Really sorry for not taking out the time to address this sooner.

**Comment by MustansirZia** [comment]
Okay, so I've had time to look into this issue and it seems there, in fact, there is is no heading property available to us. That's how it has been since the beginning, what's weird is it crept in the docs as a typo and has renamined there since then. 

However, I think what you're looking for is the [`bearing`](https://developer.android.com/reference/android/location/Location.html#getBearing()) property. Do check it out. 
And thanks for pointing this out. Going to close the issue.
