### ISSUE TITLE
On same place latitude longitude are different every time.

### ISSUE THREAD

**Issue by DY205** [MustansirZia/react-native-fused-location#46]
**Getting location through android device placing at the same place , but get different lat. long. with few margin.**
i.e-
"CheckInLat":"28.5485823","CheckInLong":"77.2523087" 
"CheckOutLat":28.5485999,"CheckOutLong":77.2523079

 FusedLocation.setLocationPriority(FusedLocation.Constants.HIGH_ACCURACY);
        // Get location once. works offline 
        const location = await FusedLocation.getFusedLocation();
        if(this.state.flag=='0'){
          this.setState({ isLoading:false,latitude: location.latitude, longitude: location.longitude});
        }else{
          this.setState({ isLoading:false,CheckOutLat: location.latitude, CheckOutLong: location.longitude});
        }

  // Set options.
  FusedLocation.setLocationPriority(FusedLocation.Constants.BALANCED);
  FusedLocation.setLocationInterval(20000);
  FusedLocation.setFastestLocationInterval(15000);
  FusedLocation.setSmallestDisplacement(10);
  // Keep getting updated location.
  FusedLocation.startLocationUpdates();
   // Place listeners.
  this.subscription = FusedLocation.on('fusedLocation', location => {
  if(this.state.flag=='0'){
    this.setState({ isLoading:false,latitude: location.latitude, longitude: location.longitude});
  }else{
    this.setState({ isLoading:false,CheckOutLat: location.latitude, CheckOutLong: location.longitude});
  }
 })

**Comment by MustansirZia** [comment]
Hi @DY205!

Well, I can see you're using different values for `setLocationPriority` for both these calls. In that case, it is quite obvious you're going to get different values for latitude or longitude. A more accurate location will be somewhat different than a less accurate location at the same place and vice versa. 

Also, it is quite possible that the values might be slightly different from each other for the same accuracy level if there's a slight time gap between the calls. There is always a small margin for error since there are hardware limitations.

**Comment by DY205** [comment]
ok, thanks for quick reply,
one more thing is there any case when i am getting null location
i.e-  CheckInLat":null,"CheckInLong":null

**Comment by MustansirZia** [comment]
No, I don't think that will be the case. It's either going to be a valid location or the method will reject its returned promise.

**Comment by DY205** [comment]
ok thanks
